version: '3.8'

services:
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # flask-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     MONGO_URI: "mongodb://mongo:27017/mini_wallet_db"  # Set the MongoDB URI here
  #   depends_on:
  #     - mongo


volumes:
  mongo-data:
